export const options = [
  {
    id: 1,
    title: 'Mis datos',
    color: '#E74C3C',
    options: 'Ver mis datos, modificar datos, cambiar contraseña',
    image: 'https://img.icons8.com/office/512/user-menu-male--v1.png',
    route: 'Profile',
    // image: 'https://img.icons8.com/color/70/000000/name.png',
  },
  {
    id: 1,
    title: 'Usuarios',
    color: '#87CEEB',
    options: 'Listar usuarios y opciones',
    image: 'https://img.icons8.com/office/512/groups.png',
    route: 'Users',
    // image: 'https://img.icons8.com/office/70/000000/home-page.png',
  },
  {
    id: 2,
    title: 'Registrar nuevo usuario',
    color: '#4682B4',
    options: 'Registrar nuevo usuario',
    image: 'https://img.icons8.com/officel/512/add-user-male.png',
    route: 'UserForm',
    //https://img.icons8.com/color/70/000000/two-hearts.png',
  },
  {
    id: 3,
    title: 'Todas las planillas',
    color: '#6A5ACD',
    options: 'Ver todas las planillas registradas',
    image: 'https://img.icons8.com/office/512/report-card.png',
    route: 'AllTemplates',
    //image: 'https://img.icons8.com/dusk/70/000000/checklist.png',
    //image: 'https://img.icons8.com/color/70/000000/family.png',
  },
  {
    id: 4,
    title: 'Roles del sistema',
    color: '#FF69B4',
    options: 'Ver roles del sistema',
    image: 'https://img.icons8.com/office/512/user-shield.png',
    route: 'RolesList',
    //image: 'https://img.icons8.com/color/70/000000/groups.png',
  },
];
