export const options = [
    {
        id: 1,
        title: 'Mis datos',
        color: '#FF4500',
        options: 'Ver mis datos, modificar datos, cambiar contraseña',
        image: 'https://img.icons8.com/office/512/user-menu-male--v1.png',
        route: 'Profile',
        // image: 'https://img.icons8.com/color/70/000000/name.png',
    },
    {
        id: 1,
        title: 'Mis planillas',
        color: '#87CEEB',
        options: 'Listar todas mis planillas registradas',
        image: 'https://img.icons8.com/office/512/groups.png',
        route: 'NutricionistList',
        // image: 'https://img.icons8.com/office/70/000000/home-page.png',
    },
    {
        id: 2,
        title: 'Registrar nueva planilla',
        color: '#4682B4',
        options: 'Registrar nueva planilla',
        image: 'https://img.icons8.com/officel/512/add-user-male.png',
        route: 'CreateTemplateNutricionist',
        //https://img.icons8.com/color/70/000000/two-hearts.png',
    } 
    /*
      {
        id: 3,
        title: 'Todas las planillas',
        color: '#6A5ACD',
        options: 'Ver todas las planillas registradas',
        image: 'https://img.icons8.com/office/512/report-card.png',
        route: 'AllTemplates',
        //image: 'https://img.icons8.com/dusk/70/000000/checklist.png',
        //image: 'https://img.icons8.com/color/70/000000/family.png',
      },
      {
        id: 4,
        title: 'Roles del sistema',
        color: '#FF69B4',
        options: 'Ver roles del sistema',
        image: 'https://img.icons8.com/office/512/user-shield.png',
        route: 'RolesList',
        //image: 'https://img.icons8.com/color/70/000000/groups.png',
      },
      {
        id: 5,
        title: 'School',
        color: '#00BFFF',
        members: 7,
        image: 'https://img.icons8.com/color/70/000000/classroom.png',
      },
      {
        id: 6,
        title: 'Things',
        color: '#00FFFF',
        members: 8,
        image: 'https://img.icons8.com/dusk/70/000000/checklist.png',
      },
      {
        id: 8,
        title: 'World',
        color: '#20B2AA',
        members: 23,
        image: 'https://img.icons8.com/dusk/70/000000/globe-earth.png',
      },
      {
        id: 9,
        title: 'Remember',
        color: '#191970',
        members: 45,
        image: 'https://img.icons8.com/color/70/000000/to-do.png',
      },
      {
        id: 9,
        title: 'Game',
        color: '#008080',
        members: 13,
        image: 'https://img.icons8.com/color/70/000000/basketball.png',
      },*/,
];